# Generated by Django 5.0.4 on 2024-05-04 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tallyitem",
            name="person",
        ),
        migrations.AddField(
            model_name="tallyitem",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tally",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
