# Generated by Django 5.0.4 on 2024-05-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drinks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AddField(
            model_name="drink",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="drink",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
