name: Main Workflow

on: [push, pull_request]

jobs:
  select-jobs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Test
      id: test
      uses: ./.github/actions/changed-files

    - name: Check for changes
      id: changes
      run: |
        files_to_watch=$(cat .github/config/files_build_docker.txt | tr '\n' ' ')
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        for file in $files_to_watch; do
          if echo "$changed_files" | grep -q "$file"; then
            echo "build_docker=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        done
        echo "build_docker=false" >> "$GITHUB_OUTPUT"

  build-docker:
    runs-on: ubuntu-latest
    needs: select-jobs
    if: needs.select-jobs.outputs.build_docker == 'true'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Docker Build
      run: |
        ./build_docker.sh