name: Changed Files

outputs:
  head-sha:
    value: ${{ steps.get-head-sha.outputs.head-sha }}
  base-sha:
    value: ${{ steps.get-base-sha.outputs.base-sha }}
  changed-files:
    value: ${{ steps.get-changed-files.outputs.changed-files }}

runs:
  using: composite
  steps:
    - id: get-head-sha
      name: "Get head sha for git diff"
      shell: bash
      run: |
        echo "::group::Get head SHA"
        HEAD_SHA=""
        if [[ "${{ github.events.pull_request.head.sha }}" != "" ]]; then
          HEAD_SHA=${{ github.events.pull_request.head.sha }}
        elif [[ "${{ github.event.after }}" != "" ]]; then
          HEAD_SHA=${{ github.event.after }}
        elif [[ "${{ github.sha }}" != "" ]]; then
          HEAD_SHA=${{ github.sha }}
        else
          echo "ERROR: Could not determine head sha."
          exit 1
        fi
        echo "head-sha: $HEAD_SHA"
        echo "head-sha=$HEAD_SHA" >> "$GITHUB_OUTPUT"

    - id: get-base-sha
      name: "Get base sha for git diff"
      shell: bash
      run: |
        echo "::group::Get base SHA"
        BASE_SHA=""
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BASE_SHA=$(git -C ${GITHUB_WORKSPACE} merge-base origin/${{ github.event.repository.default_branch }} ${{ steps.get-head-sha.outputs.head-sha }})
        elif [[ "${{ github.event.before }}" != "" ]]; then
          BASE_SHA=${{ github.event.before }}
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref }}" == "refs/head/${{ github.event.repository.default_branch }}" ]]; then
          BASE_SHA=$(git -C ${GITHUB_WORKSPACE} rev-parse HEAD~1)
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref }}" != "refs/head/${{ github.event.repository.default_branch }}" ]]; then
          BASE_SHA=$(git -C ${GITHUB_WORKSPACE} merge-base origin/${{ github.event.repository.default_branch }} ${{ steps.get-head-sha.outputs.head-sha }})
        else
          echo "ERROR: Could not determine base sha."
          exit 1
        fi
        echo "base-sha: $BASE_SHA"
        echo "base-sha=$BASE_SHA" >> "$GITHUB_OUTPUT"

    - id: get-changed-files
      name: "Get changed files"
      shell: bash
      run: |
        git -C ${GITHUB_WORKSPACE} status > /dev/null 2>&1
        if [[ $? -ne 0 ]]; then
          echo "ERROR: No repository was checked out. Make sure to call the checkout action first."
          exit 1
        fi

        echo "::group::Fetching head and base commit"
        git -C ${GITHUB_WORKSPACE} fetch --depth=1 origin ${{ steps.get-head-sha.outputs.head-sha }}
        git -C ${GITHUB_WORKSPACE} fetch --depth=1 origin ${{ steps.get-base-sha.outputs.base-sha }}

        echo "::group::Determine changed files"
        CHANGED_FILES=$(git -C ${GITHUB_WORKSPACE} diff --name-only ${{ steps.get-base-sha.outputs.base-sha }}..${{ steps.get-head-sha.outputs.head-sha }})
        echo "changed files: $CHANGED_FILES"
        echo "changed-files=$CHANGED_FILES" >> "$GITHUB_OUTPUT"